### ISSUE TITLE
USER STORY: Understanding Yoga Fitness

### ISSUE THREAD

**Issue by email2ify** [email2ify/My-Yoga#1]
As a **Site User** I can **view and read what the Yoga Fitness is all about** so that **I can navigate through it and read more about it and if possible add comments to it**

## Acceptance Criteria:

- **Acceptance Criteria 1**: The site should be able to display properly
* **Acceptance Criteria 2**: The site should have a markdown menu, to navigate
- **Acceptance Criteria 3**: The site should have a header about the image
+ **Acceptance Criteria 4**: The site should have a waiting list box and a community section

## Tasks:

- [ ] Design user interface for the site
- [ ] Create HTML,CSS and JAVASCRIPT
- [ ] Create the Navbar
- [ ] Create code for the Model, viewer
- [ ] Test the functionality
