### ISSUE TITLE
USER STORY: To view joining list

### ISSUE THREAD

**Issue by email2ify** [email2ify/My-Yoga#2]
As a **Site User** I can **join the waiting list** so that I can **participate in the next yoga fitness training**

## Acceptance Criteria:

- **Acceptance Criteria 1**: The site should have a waiting list field to join the community for the next yoga meeting

## Tasks:

- [ ] Design user interface for the site
- [ ] Create HTML,CSS and JAVASCRIPT
- [ ] Create a field in the model to track the email addresses
- [ ] Test the functionality
