### ISSUE TITLE
USER STORY: Register an account

### ISSUE THREAD

**Issue by email2ify** [email2ify/My-Yoga#3]
As a **Site User** I can **register an account** so that I can **testify in the yoga blogs**

## Acceptance Criteria:

- **Acceptance Criteria 1**: The site should be able to enter user name to create an account.

## Tasks:

- [ ] Design user interface for the site
- [ ] Create HTML,CSS and JAVASCRIPT
- [ ] Create a field in the model to track the username
- [ ] Test the functionality
