### ISSUE TITLE
USER STORY: Manage Post

### ISSUE THREAD

**Issue by email2ify** [email2ify/My-Yoga#4]
As a **Site User** I can ** read what the yoga blog, read testimonies, or add a testimony to the comment section. ** so that ** I can reflect to what I have posted and go back to the post to update or delete if need be**

## Acceptance Criteria:

- **Acceptance Criteria 1**: The site should be able to create, read, update, and delete testimonies or comment post
 - **Acceptance Criteria 2**: The site should have character field password
 -  **Acceptance Criteria 3**: The site blogs should have a date

## Tasks:

- [x] Create a crud function for post
- [x] Create a place holder, text field and username
- [ ] Test the functionality
