### ISSUE TITLE
USER STORY: Admin accessing user

### ISSUE THREAD

**Issue by email2ify** [email2ify/My-Yoga#5]
As a **User/Admin** I can **view registered email addresses and user names** so that **I can have counts of registered email addresses and usernames**

## Criteria:

- **Criteria 1**: The admin should be able to modify and see registered email addresses/usernames from the database

## Tasks:

- [ ] Using postgres to the Database
- [ ] Create HTML,CSS, JAVASCRIPT and PYTHON
- [ ] Create a field in the model to track the email addresses in the database
- [ ] Test the functionality
